language: bash

services:
- docker

env:
  matrix:
  - REDIS_VER=5.0.6 TAGS=5.0,5,latest
  - REDIS_VER=4.0.14 TAGS=4.0,4

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
