language: bash

services:
- docker

env:
  matrix:
  - REDIS_VER=6.0.7 TAGS=6.0,6,latest
  - REDIS_VER=5.0.9 TAGS=5.0,5

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
