language: bash

services:
  - docker

env:
  matrix:
    - REDIS_VER=5.0.2 TAGS=5.0,5,latest
    - REDIS_VER=4.0.11 TAGS=4.0,4

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
