language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4.0
  matrix:
    - TAG=4.0 REDIS_VER=4.0.8 EXTRA_TAG=4
    - TAG=3.2 REDIS_VER=3.2.11 EXTRA_TAG=3

script:
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export STABILITY_TAG="${TRAVIS_TAG}"
    fi

    make release

    if [[ -n "${EXTRA_TAG}" ]]; then
      make release TAG="${EXTRA_TAG}"
    fi

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi

notifications:
  on_failure: never
  slack:
    secure: |
      dW+ZW7nu+EikU6d2meYDncgZ9XA7+3Awma6ZuM15+e+mXSfC5d9mTof2PcWl4leBNdSA6TxSmVi50A6ezc8m2Msbcu1Vk63gUdXeco2uQOTp/eECXoD+DQ2807QtG2n6QKx2+wFwMzg4TR70czRiG3tRwHO5VpO8iIIEpnaHIup5kCmKE82uKUOqWbkqo0zzq7ReIXiDIaabK4Lf1WL/17CTeYIK4QM1IR3IN5W+JhV32ChYqLIDOE2rAXCxCMmheyYmWlPMVx1KwzNZCg61KBNvcyLQ/5ZkZyTSgkAJF7LKwaX+/Q6SX29vKToZR1mVnc8mqiiu8pTGJDboSCWrHHciPj++b+tZz3WouRI2VePlmZrZ57nWQMfB/Z5Ttz5mrDxW2sjSulp2mHFaGvZqGpersNiSbdoMuMTfssV84mYR7NMoP4ajnK+hMiYSEjH0NiA8RG6EjkAgdrS8v6QlM4YevUkzU6Zc8JVA+6HxAGVEFKi89omVopgpT0ZDh3JvbjdZWAXvXNRfGxNsJFR5Dy9u6yjB4EqWr8E0iZaEvBvJgHJHsAhiaWKB61Q+z0vS71iulvxvFqhmLYhCkxdyBHNOmGyi5DJNxt3FF18GV+okJ47rO2brSxdzXNomd09cIPDJN+r42l1MqYJKILUcDaqeQe7vwP0XND08wegOlPM=